spring:
  data:
    mongodb:
      uri: "mongodb://root:root123@kancy.top:27017/test?authSource=admin"
  rabbitmq:
    host: kancy.top
    port: 5672
    username: root
    password: root123
    virtual-host: /delay-message-db

delay:
  message:
    datasource:
      master:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.139.60.82:3306/delay_message_db?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
        username: root
        password: root123
        hikari:
          max-pool-size: 5
          min-idle: 1
      slave:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.139.60.82:3306/delay_message_db?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
        username: root
        password: root123
        hikari:
          max-pool-size: 5
          min-idle: 1
    scheduler:
      min-reset-message-status-time: 1s
      max-reset-message-status-time: 5s
      min-refresh-min-expired-time: 1s
      max-refresh-min-expired-time: 5s
