spring:
  data:
    mongodb:
      uri: "mongodb://root:root123@kancy.top:27017/test?authSource=admin"
  rabbitmq:
    host: kancy.top
    port: 5672
    username: root
    password: root123
    virtual-host: /delay-message-db
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://kancy.top:3306/delay_message_db?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
          username: root
          password: root123
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:mysql://kancy.top:3306/delay_message_db?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
          username: root
          password: root123
          driver-class-name: com.mysql.cj.jdbc.Driver
delay:
  message:
    datasource:
      master:
        reference: master
      slave:
        url: jdbc:mysql://kancy.top:3306/delay_message_db?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
        username: root
        password: root123
        driver-class-name: com.mysql.cj.jdbc.Driver
    scheduler:
      min-reset-message-status-time: 1s
      max-reset-message-status-time: 5s
      min-refresh-min-expired-time: 1s
      max-refresh-min-expired-time: 5s
