spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: "mongodb://root:root123@kancy.top:27017/test?authSource=admin"
  rabbitmq:
    host: kancy.top
    port: 5672
    username: root
    password: root123
    virtual-host: /delay-message-db

delay:
  message:
    datasource:
      master:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://kancy.top:3306/delay_message_db?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
        username: root
        password: root123

logging:
  level:
    org.springframework: info
